### ISSUE TITLE
tag system in db

### ISSUE THREAD

**Issue by morkeltry** [FAC-11/litlearn#19]
many to many
Question <-> tag name/type
Include int (100% for user set, else no. thumbsup)

Possible:
include list of users who thumbsupped

**Comment by rachaelcodes** [comment]
@rachaelcodes needs to provide list of suitable GCSE-related tags

**Comment by rachaelcodes** [comment]
Suggested questions (with tags)

**Question 1**
'During the whole of a dull, dark, and soundless day in the autumn of the year, when the clouds hung oppressively low in the heavens, I had been passing alone, on horseback, through a singularly dreary tract of country; and at length found myself, as the shades of the evening drew on, within view of the melancholy House of Usher. I know not how it was -- but, with the first glimpse of the building, a sense of insufferable gloom pervaded my spirit.'

This extract is the opening of a story by Edgar Allen Poe. Which word do you feel best describes the atmosphere of this scene?
- miserable
- happy
- creepy
- tense

*How does the writer describe the weather? What mood does that give?*

Language, Edexcel, 19th Century, Fiction, analysis

**Question 2**
'The dialogue is often good. At the end of the first act it is as salt* and rapid as good comedy dialogue should be. Elsewhere it is several times forced and tedious beyond expression, and in the third act one long passage of highly worked-up witticisms, during the delivery of which the action makes almost a dead halt, is intolerably artificial in its own substance and still more in the crude and unprepared manner of its introduction. *salt = rude'

This extract is from the review of a play. What seems to be the reviewer's opinion of the play?
- They love it
- They mostly like it
- They mostly dislike it
- They hate it

*This extract talks about the dialogue (words) in the play. How much does the reviewer say is good and how much do they say is bad writing?*

Language, AQA, EDUQAS, OCR, 19th Century, Non-Fiction, inference

**Question 3**
'Tybalt: What, art thou drawn among these heartless hinds? 
Turn thee, Benvolio, look upon thy death. <br>
Benvolio: I do but keep the peace: put up thy sword, 
Or manage it to part these men with me.'
What is the relationship between Benvolio and Tybalt in this scene?
- They are good friends
- Tybalt wants to fight, but Benvolio doesn't
- Benvolio wants to fight, but Tybalt doesn't
- They both want to fight

*Both men give an instruction to the other. What does each one say?*

Literature, AQA, EDUQAS, OCR, EDEXCEL, Romeo and Juliet, inference
