### ISSUE TITLE
Filter questions based on user preferences 

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/litlearn#2]
Includes: #21 #22 #23 #24
User Story: "I can see a list of questions and easily filter them - by English GCSE skill, by text type and text age"

Things we need to achieve from this issue: 
 - [ ] list of questions
 - [ ] filter buttons
 - [ ] filter buttons separated by headings for type of filter
 - [ ] filter function

**Comment by rachaelcodes** [comment]
duplicates #21 #22 #23
