### ISSUE TITLE
Set up external sites

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/litlearn#31]
- [x] Heroku
- [x] Travis
- [x] CodeCov?

**Comment by Jen-Harris** [comment]
I attempted to set up Heroku and Travis but have come across issues that I cannot resolve. 

We are all admins so can be viewed by anyone can help!

@rachaelcodes thanks for pointing out some of the obvious issues :blush:

**Comment by Jen-Harris** [comment]
Update: Heroku now working!

**Comment by Jen-Harris** [comment]
Nice job @rachaelcodes 👍 👍 👍
