### ISSUE TITLE
Create navigation bar

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/litlearn#6]
**User Stories**
* I want to be able to easily navigate around the site 

**Requirements**
- [x] There should be an easy to understand nav bar 
- [x] Depending on the page will include links to: home, hints, next page and previous page

updates:
- [x] alter hrefs so that it is on the entire div not just logo 
- [x] for multichoice page handle the case where an option hasn't been selected. either: error message or only show next button when an answer has been selected
- [x] hide submit button so that you can only see the arrow
- [x] currently submit button image is not aligning correctly - this needs fixing

**Comment by Jen-Harris** [comment]
awaiting correct href inputs from @morkeltry
