### ISSUE TITLE
create system for preserving answer variable

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/litlearn#7]
* if I go back to the multiple choice question and change my answer, my answer will be updated in the 'extract explanation' screen

**Comment by rachaelcodes** [comment]
I've labeled this as question as I'm not fully sure how we will do this - will it involve having states or user variables?

**Comment by rachaelcodes** [comment]
local storage! (can we also use this for tracking session time?) thanks @Jen-Harris !

**Comment by morkeltry** [comment]
Done MVP of this issue
-requires user to allow sessionStorage (in Chrome this comes under 3rd party cookies)
