### ISSUE TITLE
Create hints modal

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/litlearn#8]
**User Story**
* I can see hints to questions when I get confused or stuck
**Requirements**
- [x] The hints should be navigated to from the nav bar 
- [x] A user should be able to exit the hint by clicking anywhere on the screen 
- [x] The hint should be relevant to the current question 
- [x] The icon should be a lightbulb and also have text saying 'hint' to add clarity
- [ ] Should be styled as per the design in Figma
![image](https://user-images.githubusercontent.com/26116988/30375733-9a0589c4-9881-11e7-82f8-48b8f65c2bbe.png)

**Comment by Jen-Harris** [comment]
Not styled as per Figma design - I have created a more plain modal 
![image](https://user-images.githubusercontent.com/26116988/30383616-0463f41e-989a-11e7-8e7c-6abd0cb33c7b.png)
